# Generated by Django 5.0.14 on 2026-06-25 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('WHATSAPP_CLICK', 'WhatsApp CTA Click'), ('PHONE_CLICK', 'Phone Call Click'), ('IMAGE_VIEW', 'Image Full View')], max_length=50)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile Phone'), ('DESKTOP', 'Desktop / Laptop'), ('TABLET', 'Tablet')], default='MOBILE', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='properties.property')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
