[mypy]
plugins =
    mypy_django_plugin.main

strict_optional = True
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = False
disallow_untyped_calls = False
disallow_incomplete_defs = False
warn_redundant_casts = True
warn_unused_ignores = True

[mypy.plugins.django-stubs]
django_settings_module = "property_os.settings"
