# Generated by Django 5.0.14 on 2026-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('phone_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('COLLECTING', 'Collecting Details')], default='IDLE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('temp_images', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
