# Generated by Django 5.0.14 on 2026-06-26 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('COLLECTING', 'Collecting Details'), ('UPDATING', 'Updating Listing'), ('QUERYING', 'Querying Inventory')], default='IDLE', max_length=20),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(default='TEXT', max_length=20)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_url', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
