# Generated by Django 5.0.14 on 2026-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutableAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('current_hash', models.CharField(db_index=True, max_length=64)),
                ('signature', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
