# Generated by Django 5.0.14 on 2026-06-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment / Flat'), ('VILLA', 'Villa / House'), ('PLOT', 'Land / Plot'), ('COMMERCIAL', 'Commercial Space')], default='APARTMENT', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('NEGOTIATION', 'In Negotiation'), ('SITE_VISIT', 'Site Visit Scheduled'), ('BOOKED', 'Booked / Token Received'), ('SOLD', 'Sold / Closed')], default='AVAILABLE', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('bhk', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
