# Generated by Django 5.0.14 on 2026-06-26 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def backfill_property_data(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    AnalyticsEvent = apps.get_model('analytics', 'AnalyticsEvent')
    
    # Use try-except in case leads app is not yet available in the migration context
    try:
        Lead = apps.get_model('leads', 'Lead')
    except LookupError:
        Lead = None

    from datetime import timedelta
    
    for p in Property.objects.all():
        # Expiry backfill
        if not p.expires_at:
            expiry_days = 30
            if hasattr(p, 'tenant') and p.tenant:
                expiry_days = p.tenant.listing_expiry_days
            p.expires_at = p.created_at + timedelta(days=expiry_days)
            
        # Views count backfill
        p.views_count = AnalyticsEvent.objects.filter(property=p, event_type='PAGE_VIEW').count()
        
        # Leads count backfill
        if Lead:
            p.leads_count = Lead.objects.filter(property=p).count()
        else:
            p.leads_count = 0
            
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('analytics', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='leads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NEGOTIATION', 'In Negotiation'), ('SITE_VISIT', 'Site Visit Scheduled'), ('BOOKED', 'Booked / Token Received'), ('SOLD', 'Sold / Closed'), ('EXPIRED', 'Expired / Delisted')], default='AVAILABLE', max_length=20),
        ),
        migrations.RunPython(backfill_property_data, reverse_code=migrations.RunPython.noop),
    ]
