# Generated by Django 5.0.14 on 2026-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='listing_expiry_days',
            field=models.IntegerField(default=30),
        ),
    ]
