# Generated by Django 5.0.14 on 2026-07-20

from django.db import migrations

def migrate_logo_urls(apps, schema_editor):
    try:
        Tenant = apps.get_model('accounts', 'Tenant')
    except LookupError:
        return

    old_domain = "storage.supabase.co/storage/v1/s3"
    new_domain = "supabase.co/storage/v1/object/public"
    
    for tenant in Tenant.objects.all():
        if tenant.logo_url and old_domain in tenant.logo_url:
            tenant.logo_url = tenant.logo_url.replace(old_domain, new_domain)
            tenant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_mfa_enabled_user_mfa_secret_user_mfa_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_logo_urls, elidable=True),
    ]
