# Generated by Django 5.0.14 on 2026-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New / Uncontacted'), ('CONTACTED', 'Contacted / Active'), ('SITE_VISIT', 'Site Visit Scheduled'), ('NEGOTIATION', 'In Negotiation'), ('CLOSED', 'Closed / Won'), ('LOST', 'Lost / Not Interested')], default='NEW', max_length=20),
        ),
    ]
