# Generated by Django 5.0.14 on 2026-07-20

from django.db import migrations

def migrate_urls(apps, schema_editor):
    try:
        PropertyImage = apps.get_model('media', 'PropertyImage')
    except LookupError:
        # App might not be loaded in this context or model name differs
        return

    old_domain = "storage.supabase.co/storage/v1/s3"
    new_domain = "supabase.co/storage/v1/object/public"
    
    for img in PropertyImage.objects.all():
        updated = False
        if img.url and old_domain in img.url:
            img.url = img.url.replace(old_domain, new_domain)
            updated = True
        if img.thumbnail_url and old_domain in img.thumbnail_url:
            img.thumbnail_url = img.thumbnail_url.replace(old_domain, new_domain)
            updated = True
        if updated:
            img.save()

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_urls, elidable=True),
    ]
