export type Language = 'en' | 'hi' | 'mr';

export function parseLanguage(value: string | null): Language {
  return value === 'hi' || value === 'mr' ? value : 'en';
}

export const COPY = {
  en: {
    nav: ['Product', 'How it works', 'Pricing', 'FAQs'], login: 'Log in', start: 'Start free trial', menu: 'Menu', close: 'Close', language: 'Language', skip: 'Skip to content',
    eyebrow: 'FOR INDEPENDENT REAL ESTATE BROKERS', headline: 'Your real estate business, online.',
    intro: 'Branded property pages. WhatsApp sharing. Enquiries in one place. Give every listing a professional home, from apartments to commercial spaces and land.',
    explore: 'Explore sample listings', reassurance: '14-day assisted trial · No card required', categories: ['Residential', 'Commercial', 'Plots & land'],
    trustItems: [
      ['60-Second Setup', 'No coding or agency fees needed'],
      ['WhatsApp-First', '1-tap client sharing with live preview'],
      ['100% Private Data', 'Your leads & phone contacts stay yours'],
      ['0% Brokerage Cut', 'Keep all your deal commission'],
    ],
    walkthroughEyebrow: 'FROM LISTING TO CONVERSATION',
    walkthroughTitle: 'How PropertyOS works.',
    walkthroughSteps: [
      {
        label: 'Listing Preparation',
        title: 'Add your property details',
        description: 'Upload photos and fill in the essentials: price, location, area and property type. The platform formats them into a clean, shareable page.',
        previewLabel: 'Property form',
        previewSub: '₹1.65 Cr · 3 BHK · Baner, Pune',
      },
      {
        label: 'Branded Page Preview',
        title: 'Review your branded page',
        description: 'Your agency name and contact details appear on every listing. Check the layout, update the description and publish when ready.',
        previewLabel: 'Live page',
        previewSub: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'WhatsApp Share',
        title: 'Share the link on WhatsApp',
        description: 'Copy a prepared message with the property link and send it to buyers. They see your branded page — not a third-party portal.',
        previewLabel: 'Copy message',
        previewSub: 'propertyos.in/p/prime-baner 🏡',
      },
      {
        label: 'Captured Enquiry',
        title: 'Follow up with context',
        description: 'When a buyer fills the enquiry form on your page, you see their name, note and which property they asked about — all in one place.',
        previewLabel: 'New enquiry',
        previewSub: 'Rohan M. · Baner 3 BHK · Visit request',
      },
    ],
    walkthroughVisuals: [
      { badge: 'Step 01 · Input', heading: 'Property Form', meta: '6 Photos · ₹1.65 Cr · Baner, Pune', tag: 'Auto-formatted' },
      { badge: 'Step 02 · Share', heading: 'Live Branded Page', meta: 'propertyos.in/p/prime-baner', tag: '1-Click WhatsApp' },
      { badge: 'Step 03 · Grow', heading: 'Direct Buyer Lead', meta: 'Rohan M. • Site visit request', tag: 'Instant Alert' },
    ],
    waDemoEyebrow: 'WHATSAPP SHARING — HOW IT WORKS',
    waDemoTitle: 'Share a property in four steps.',
    waDemoNote: 'This is a controlled example. No message is sent automatically.',
    waDemoSteps: [
      {
        label: 'Prepare',
        heading: 'Pick the property to share',
        body: 'Choose the listing from your dashboard. PropertyOS builds a ready-to-send message with the branded page link.',
        visual: 'Garden Residence in Baner · ₹1.65 Cr · 3 BHK',
      },
      {
        label: 'Copy message',
        heading: 'Copy the prepared message',
        body: 'A message is pre-written with the property link. Tap "Copy" and paste it into any WhatsApp conversation.',
        visual: 'Hi! Check out this 3 BHK in Baner, Pune:\npropertyos.in/p/prime-baner 🏡\nReach out if you\'d like to visit.',
      },
      {
        label: 'Buyer preview',
        heading: 'Buyer opens your branded page',
        body: 'The link opens your branded listing page — photos, price, specs and an enquiry form. Your name and number are front and centre.',
        visual: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'Enquiry context',
        heading: 'You see the enquiry with context',
        body: 'When the buyer submits the form, you receive their name, note and which listing they asked about — no back-and-forth needed.',
        visual: 'Rohan M. · "Interested in a site visit this weekend." · Baner 3 BHK',
      },
    ],
    waDemoCopy: 'Copy message',
    waDemoCopied: 'Copied!',
    waDemoCopyError: 'Could not copy. Select and copy the text manually.',
    aiDemoEyebrow: 'AI-ASSISTED DESCRIPTIONS',
    aiDemoTitle: 'From details to a draft in seconds.',
    aiDemoNote: 'Example output — always review the facts before publishing.',
    aiDemoLabel: 'Example output',
    aiDemoInputs: {
      type: 'Property type',
      bedrooms: 'Bedrooms',
      area: 'Area',
      location: 'Location',
      price: 'Price',
    },
    aiDemoOptions: {
      type: ['Residential', 'Commercial', 'Land'],
      bedrooms: ['1 BHK', '2 BHK', '3 BHK', '4+ BHK', 'N/A'],
    },
    aiDemoDefaults: { type: 'Residential', bedrooms: '3 BHK', area: '1,460 sq ft', location: 'Baner, Pune', price: '₹1.65 Cr' },
    aiDemoOutput: 'A well-maintained 3 BHK apartment in the sought-after Baner neighbourhood of Pune. The 1,460 sq ft layout includes three bedrooms, a living area and a kitchen. Priced at ₹1.65 Cr. Located in Baner with easy access to key corridors. Suitable for families and working professionals. Contact for a site visit.',
    aiDemoOutputLabel: 'Draft description',
    aiDemoDisclaimer: 'Review all facts — price, area, location and amenities — before publishing. The draft is a starting point, not a verified listing.',
    pricingBadges: {
      proBadge: 'Founding Offer — First 100 Brokers',
      zeroCut: 'Zero commission on leads & client transactions',
    },
    portfolioEyebrow: 'YOUR BRAND. EVERY LISTING.', portfolioTitle: 'A better first impression. A clearer next step.',
    portfolioIntro: 'Explore illustrative property pages for three different kinds of business.', sample: 'Sample portfolio', agency: 'Prime Realty', agencyLocation: 'Pune, Maharashtra',
    sampleNote: 'Illustrative listings and photography. These properties are not offered for sale or rent.', all: 'All properties', filter: 'Property type', view: 'View property', details: 'Property details',
    titles: ['Garden residence in Baner', 'Workspace in Kharadi', 'Land parcel near Mulshi'], locations: ['Baner, Pune', 'Kharadi, Pune', 'Mulshi, Pune'],
    prices: ['₹1.65 Cr', '₹85,000 / month', '₹72 lakh'], statuses: ['For sale', 'For lease', 'For sale'],
    specs: [['3 bedrooms', '1,460 sq ft', 'Ready to move'], ['1,200 sq ft', 'Office space', 'Unfurnished'], ['4,000 sq ft', 'Land parcel', 'Road access']],
    descriptions: ['An illustrative residence with bright living spaces and a garden. A property page brings photos, area, price and contact details together.', 'An illustrative office listing with floor area, furnishing and lease price. Commercial details take priority over residential fields.', 'An illustrative land listing with area and access details. Land use, title and permissions must be independently verified before a transaction.'],
    createLike: 'Create your own listing', copy: 'Copy sample link', copied: 'Link copied', copyError: 'Could not copy. Copy the address from your browser.',
    howEyebrow: 'FROM LISTING TO CONVERSATION', howTitle: 'One straightforward workflow.',
    steps: [['Add your property', 'Upload photos and the relevant details: price, location, area and property type.'], ['Review and share', 'Refine your description, publish a branded page and send the link through WhatsApp.'], ['Follow up with context', 'Review captured enquiries and buyer actions, then organise your next conversation.']],
    featuresEyebrow: 'BUILT AROUND YOUR WORKDAY', featuresTitle: 'More useful after you hit share.',
    features: [['Your identity, front and centre', 'Put your agency name, logo and contact details on the pages you share.'], ['WhatsApp, with context', 'Share a property link and bring buyers back to its photos, details and enquiry action.'], ['AI-assisted descriptions', 'Create a draft from the property details you supply. Review the facts before publishing.'], ['Enquiries you can act on', 'Keep captured leads, notes and stages together. Page views are signals, not confirmed buyers.']],
    priceEyebrow: 'FOUNDING BROKER PROGRAM', priceTitle: 'Start with one real property.', priceIntro: 'Try the workflow with your own branding. Get help with your first three listings.',
    trialTitle: 'Assisted trial', trialPrice: 'Free', trialPeriod: 'for 14 days', trialFeatures: ['Up to 10 listings', 'Up to 2 workspace users', 'Up to 50 leads', 'Branded pages and sharing'],
    paidTitle: 'Founding Pro', paidPrice: '₹499', paidPeriod: 'per month · assisted activation', paidFeatures: ['Up to 100 listings', 'Up to 5 workspace users', 'Up to 500 leads', 'Listing and enquiry analytics'],
    priceNote: 'Pro activation is arranged with support. Confirm applicable taxes and any additional service charges before upgrading.', talk: 'Discuss Pro access',
    faqTitle: 'Before you start.', faqs: [
      ['Is this only for residential brokers?', 'No. The product supports residential, commercial and land listings. Use the fields and descriptions relevant to each property.'],
      ['What happens after the 14-day trial?', 'The assisted trial lasts 14 days. Contact support to arrange paid access and confirm your account terms. This signup does not collect a card or start an automatic payment.'],
      ['Are WhatsApp automation and AI unlimited?', 'No unlimited allowance is promised. Sharing a link is separate from automated WhatsApp messaging. Automation requires provider setup; messaging charges and AI availability or limits should be confirmed with support.'],
      ['Do I get my own domain or broker website?', 'Branded individual property pages are available. The portfolio shown here is a sample experience. Broker subdomains and custom-domain websites are planned and are not included in the current offer.'],
      ['Can I see exactly who viewed a listing?', 'A page view does not identify a buyer. Use captured enquiries and contact actions for follow-up; anonymous views are only activity signals.'],
      ['What about 3D visits, community and legal services?', 'These are future directions, not included services. The current focus is publishing listings, sharing and managing enquiries.'],
    ],
    finalTitle: 'Make your next listing your first step.', finalText: 'Bring your photos and property details. We will help you get started.', footer: 'Made for real estate professionals.', footerLinks: ['Support', 'Privacy', 'Terms', 'Refunds'],
  },
  hi: {
    nav: ['प्रोडक्ट', 'कैसे काम करता है', 'कीमत', 'सवाल'], login: 'लॉग इन', start: 'मुफ़्त ट्रायल शुरू करें', menu: 'मेन्यू', close: 'बंद करें', language: 'भाषा', skip: 'मुख्य सामग्री पर जाएं',
    eyebrow: 'स्वतंत्र रियल एस्टेट ब्रोकर्स के लिए', headline: 'आपका रियल एस्टेट व्यवसाय, अब ऑनलाइन।',
    intro: 'आपके ब्रांड के प्रॉपर्टी पेज, WhatsApp शेयरिंग और सभी पूछताछ एक जगह। घर, कमर्शियल स्पेस और ज़मीन, हर लिस्टिंग को दें एक पेशेवर पहचान।',
    explore: 'सैंपल लिस्टिंग देखें', reassurance: '14 दिन का सहायता सहित ट्रायल · कार्ड की ज़रूरत नहीं', categories: ['आवासीय', 'कमर्शियल', 'प्लॉट और ज़मीन'],
    trustItems: [
      ['60 सेकंड में सेटअप', 'बिना कोडिंग या एजेंसी खर्च के'],
      ['WhatsApp-फ़र्स्ट', '1-टैप शेयरिंग और लाइव प्रीव्यू'],
      ['100% सुरक्षित डेटा', 'आपके ग्राहक और लीड्स निजी रहेंगे'],
      ['0% ब्रोकरेज कमीशन', 'अपनी पूरी कमाई अपने पास रखें'],
    ],
    walkthroughEyebrow: 'लिस्टिंग से बातचीत तक',
    walkthroughTitle: 'PropertyOS कैसे काम करता है।',
    walkthroughSteps: [
      {
        label: 'लिस्टिंग तैयारी',
        title: 'प्रॉपर्टी की जानकारी जोड़ें',
        description: 'तस्वीरें अपलोड करें और ज़रूरी जानकारी भरें: कीमत, स्थान, क्षेत्रफल और प्रॉपर्टी का प्रकार। प्लेटफ़ॉर्म इन्हें एक साफ़, शेयर करने योग्य पेज में बदल देता है।',
        previewLabel: 'प्रॉपर्टी फॉर्म',
        previewSub: '₹1.65 करोड़ · 3 BHK · बाणेर, पुणे',
      },
      {
        label: 'ब्रांडेड पेज प्रीव्यू',
        title: 'अपना ब्रांडेड पेज देखें',
        description: 'हर लिस्टिंग पर आपकी एजेंसी का नाम और संपर्क जानकारी दिखती है। लेआउट जांचें, विवरण सुधारें और तैयार होने पर पब्लिश करें।',
        previewLabel: 'लाइव पेज',
        previewSub: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'WhatsApp शेयर',
        title: 'WhatsApp पर लिंक शेयर करें',
        description: 'प्रॉपर्टी लिंक के साथ तैयार मैसेज कॉपी करें और खरीदारों को भेजें। वे आपका ब्रांडेड पेज देखते हैं — कोई थर्ड-पार्टी पोर्टल नहीं।',
        previewLabel: 'मैसेज कॉपी करें',
        previewSub: 'propertyos.in/p/prime-baner 🏡',
      },
      {
        label: 'पूछताछ कैप्चर',
        title: 'जानकारी के साथ फॉलो-अप करें',
        description: 'जब कोई खरीदार आपके पेज पर फॉर्म भरता है, तो आपको उनका नाम, नोट और किस प्रॉपर्टी के बारे में पूछा — सब एक जगह मिलता है।',
        previewLabel: 'नई पूछताछ',
        previewSub: 'रोहन एम. · बाणेर 3 BHK · विज़िट की दरख्वास्त',
      },
    ],
    walkthroughVisuals: [
      { badge: 'स्टेप 01 · इनपुट', heading: 'प्रॉपर्टी फॉर्म', meta: '6 तस्वीरें · ₹1.65 करोड़ · बाणेर, पुणे', tag: 'ऑटो-फॉर्मेट' },
      { badge: 'स्टेप 02 · शेयर', heading: 'ब्रांडेड लाइव पेज', meta: 'propertyos.in/p/prime-baner', tag: '1-क्लिक WhatsApp' },
      { badge: 'स्टेप 03 · लीड्स', heading: 'सीधी ग्राहक पूछताछ', meta: 'रोहन एम. • विज़िट की दरख्वास्त', tag: 'त्वरित अलर्ट' },
    ],
    waDemoEyebrow: 'WHATSAPP शेयरिंग — कैसे काम करती है',
    waDemoTitle: 'चार स्टेप में प्रॉपर्टी शेयर करें।',
    waDemoNote: 'यह एक उदाहरण है। कोई मैसेज अपने आप नहीं भेजा जाता।',
    waDemoSteps: [
      {
        label: 'तैयारी',
        heading: 'शेयर करने के लिए प्रॉपर्टी चुनें',
        body: 'डैशबोर्ड से लिस्टिंग चुनें। PropertyOS ब्रांडेड पेज लिंक के साथ एक तैयार मैसेज बनाता है।',
        visual: 'बाणेर में गार्डन वाला घर · ₹1.65 करोड़ · 3 BHK',
      },
      {
        label: 'मैसेज कॉपी करें',
        heading: 'तैयार मैसेज कॉपी करें',
        body: 'प्रॉपर्टी लिंक के साथ मैसेज पहले से लिखा होता है। "कॉपी करें" दबाएं और किसी भी WhatsApp बातचीत में पेस्ट करें।',
        visual: 'नमस्ते! बाणेर, पुणे में यह 3 BHK देखें:\npropertyos.in/p/prime-baner 🏡\nविज़िट करना हो तो बताएं।',
      },
      {
        label: 'खरीदार प्रीव्यू',
        heading: 'खरीदार आपका ब्रांडेड पेज खोलता है',
        body: 'लिंक आपके ब्रांडेड लिस्टिंग पेज पर खुलता है — तस्वीरें, कीमत, जानकारी और पूछताछ फॉर्म। आपका नाम और नंबर सबसे आगे।',
        visual: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'पूछताछ संदर्भ',
        heading: 'आप संदर्भ के साथ पूछताछ देखते हैं',
        body: 'जब खरीदार फॉर्म भरता है, तो आपको उनका नाम, नोट और किस लिस्टिंग के बारे में पूछा — कोई बार-बार पूछना नहीं।',
        visual: 'रोहन एम. · "इस वीकेंड विज़िट करना चाहूंगा।" · बाणेर 3 BHK',
      },
    ],
    waDemoCopy: 'मैसेज कॉपी करें',
    waDemoCopied: 'कॉपी हो गया!',
    waDemoCopyError: 'कॉपी नहीं हुआ। टेक्स्ट चुनकर मैन्युअली कॉपी करें।',
    aiDemoEyebrow: 'AI की मदद से विवरण',
    aiDemoTitle: 'जानकारी से मिनटों में ड्राफ्ट।',
    aiDemoNote: 'उदाहरण आउटपुट — पब्लिश करने से पहले हमेशा तथ्यों की जांच करें।',
    aiDemoLabel: 'उदाहरण आउटपुट',
    aiDemoInputs: { type: 'प्रॉपर्टी का प्रकार', bedrooms: 'बेडरूम', area: 'क्षेत्रफल', location: 'स्थान', price: 'कीमत' },
    aiDemoOptions: { type: ['आवासीय', 'कमर्शियल', 'ज़मीन'], bedrooms: ['1 BHK', '2 BHK', '3 BHK', '4+ BHK', 'लागू नहीं'] },
    aiDemoDefaults: { type: 'आवासीय', bedrooms: '3 BHK', area: '1,460 वर्ग फुट', location: 'बाणेर, पुणे', price: '₹1.65 करोड़' },
    aiDemoOutput: 'पुणे के बाणेर इलाके में एक अच्छी तरह से बनाए गए 3 BHK अपार्टमेंट में तीन बेडरूम, एक लिविंग एरिया और एक किचन है। क्षेत्रफल 1,460 वर्ग फुट है। कीमत ₹1.65 करोड़। बाणेर में मुख्य मार्गों से अच्छी कनेक्टिविटी है। परिवारों और कामकाजी पेशेवरों के लिए उपयुक्त। साइट विज़िट के लिए संपर्क करें।',
    aiDemoOutputLabel: 'ड्राफ्ट विवरण',
    aiDemoDisclaimer: 'पब्लिश करने से पहले सभी तथ्य — कीमत, क्षेत्रफल, स्थान और सुविधाएं — जांचें। ड्राफ्ट एक शुरुआत है, सत्यापित लिस्टिंग नहीं।',
    pricingBadges: { proBadge: 'फाउंडिंग ऑफर — पहले 100 ब्रोकर्स', zeroCut: 'लीड्स और सौदों पर 0% कमीशन' },
    portfolioEyebrow: 'हर लिस्टिंग पर आपका ब्रांड', portfolioTitle: 'बेहतर पहली छाप। अगला कदम साफ़।', portfolioIntro: 'तीन तरह की प्रॉपर्टी के उदाहरण देखें।', sample: 'सैंपल पोर्टफोलियो', agency: 'प्राइम रियल्टी', agencyLocation: 'पुणे, महाराष्ट्र',
    sampleNote: 'लिस्टिंग और तस्वीरें केवल उदाहरण हैं। ये प्रॉपर्टी बिक्री या किराए के लिए उपलब्ध नहीं हैं।', all: 'सभी प्रॉपर्टी', filter: 'प्रॉपर्टी का प्रकार', view: 'प्रॉपर्टी देखें', details: 'प्रॉपर्टी की जानकारी',
    titles: ['बाणेर में गार्डन वाला घर', 'खराड़ी में ऑफिस', 'मुलशी के पास ज़मीन'], locations: ['बाणेर, पुणे', 'खराड़ी, पुणे', 'मुलशी, पुणे'], prices: ['₹1.65 करोड़', '₹85,000 / महीना', '₹72 लाख'], statuses: ['बिक्री के लिए', 'लीज़ के लिए', 'बिक्री के लिए'],
    specs: [['3 बेडरूम', '1,460 वर्ग फुट', 'रहने के लिए तैयार'], ['1,200 वर्ग फुट', 'ऑफिस स्पेस', 'बिना फर्नीचर'], ['4,000 वर्ग फुट', 'ज़मीन', 'सड़क से पहुंच']],
    descriptions: ['बगीचे और रोशनी वाले कमरों के साथ एक घर का उदाहरण।', 'क्षेत्रफल, फर्निशिंग और लीज़ की कीमत के साथ ऑफिस का उदाहरण।', 'क्षेत्रफल और रास्ते की जानकारी के साथ ज़मीन का उदाहरण।'],
    createLike: 'अपनी लिस्टिंग बनाएं', copy: 'सैंपल लिंक कॉपी करें', copied: 'लिंक कॉपी हुआ', copyError: 'लिंक कॉपी नहीं हुआ। ब्राउज़र से पता कॉपी करें।',
    howEyebrow: 'लिस्टिंग से बातचीत तक', howTitle: 'एक आसान प्रक्रिया।', steps: [['प्रॉपर्टी जोड़ें', 'तस्वीरें, कीमत, स्थान, क्षेत्रफल और प्रॉपर्टी का प्रकार दर्ज करें।'], ['जांचें और शेयर करें', 'विवरण सुधारें, अपने ब्रांड का पेज पब्लिश करें और WhatsApp पर लिंक भेजें।'], ['जानकारी के साथ फॉलो-अप करें', 'पूछताछ और खरीदारों की गतिविधि देखें, फिर अगली बातचीत की तैयारी करें।']],
    featuresEyebrow: 'आपके रोज़ के काम के लिए', featuresTitle: 'शेयर करने के बाद भी उपयोगी।', features: [['आपकी पहचान सबसे आगे', 'हर पेज पर अपनी एजेंसी का नाम, लोगो और संपर्क जानकारी दिखाएं।'], ['जानकारी के साथ WhatsApp', 'एक लिंक से खरीदार को तस्वीरें, विवरण और पूछताछ का विकल्प दें।'], ['AI की मदद से विवरण', 'आपकी दी हुई जानकारी से ड्राफ्ट बनाएं। पब्लिश करने से पहले तथ्यों की जांच करें।'], ['पूछताछ पर अगला कदम', 'लीड, नोट्स और स्टेज एक जगह रखें। पेज व्यू रुचि का संकेत है, पक्का खरीदार नहीं।']],
    priceEyebrow: 'फाउंडिंग ब्रोकर प्रोग्राम', priceTitle: 'एक असली प्रॉपर्टी से शुरुआत करें।', priceIntro: 'अपने ब्रांड के साथ काम करके देखें। पहली तीन लिस्टिंग में सहायता पाएं।',
    trialTitle: 'सहायता सहित ट्रायल', trialPrice: 'मुफ़्त', trialPeriod: '14 दिनों के लिए', trialFeatures: ['10 लिस्टिंग तक', '2 यूज़र तक', '50 लीड तक', 'ब्रांडेड पेज और शेयरिंग'],
    paidTitle: 'फाउंडिंग प्रो', paidPrice: '₹499', paidPeriod: 'प्रति महीना · सहायता से एक्टिवेशन', paidFeatures: ['100 लिस्टिंग तक', '5 यूज़र तक', '500 लीड तक', 'लिस्टिंग और पूछताछ के आंकड़े'], priceNote: 'प्रो एक्टिवेशन के लिए सपोर्ट से बात करें। अपग्रेड से पहले लागू टैक्स और अतिरिक्त सेवा शुल्क की पुष्टि करें।', talk: 'प्रो के बारे में बात करें',
    faqTitle: 'शुरुआत से पहले।', faqs: [
      ['क्या यह सिर्फ़ आवासीय ब्रोकर्स के लिए है?', 'नहीं। आवासीय, कमर्शियल और ज़मीन की लिस्टिंग समर्थित हैं।'],
      ['14 दिनों के बाद क्या होगा?', 'सहायता सहित ट्रायल 14 दिन का है। पेड एक्सेस के लिए सपोर्ट से बात करें।'],
      ['क्या WhatsApp ऑटोमेशन और AI अनलिमिटेड हैं?', 'अनलिमिटेड उपयोग का वादा नहीं है। ऑटोमेशन के लिए प्रदाता सेटअप चाहिए।'],
      ['क्या मेरा अपना डोमेन या वेबसाइट मिलेगी?', 'ब्रांडेड प्रॉपर्टी पेज उपलब्ध हैं। कस्टम डोमेन भविष्य की योजना है।'],
      ['क्या हर पेज देखने वाले की पहचान मिलती है?', 'नहीं। फॉलो-अप के लिए मिली पूछताछ का उपयोग करें।'],
      ['3D विज़िट और कानूनी सेवाएं कब?', 'ये भविष्य की दिशाएं हैं, अभी शामिल नहीं हैं।'],
    ], finalTitle: 'अगली लिस्टिंग से शुरुआत करें।', finalText: 'अपनी तस्वीरें और प्रॉपर्टी की जानकारी लाएं। शुरुआत में हम मदद करेंगे।', footer: 'रियल एस्टेट पेशेवरों के लिए बनाया गया।', footerLinks: ['सपोर्ट', 'गोपनीयता', 'शर्तें', 'रिफंड'],
  },
  mr: {
    nav: ['प्रोडक्ट', 'कसे काम करते', 'किंमत', 'प्रश्न'], login: 'लॉग इन', start: 'मोफत ट्रायल सुरू करा', menu: 'मेन्यू', close: 'बंद करा', language: 'भाषा', skip: 'मुख्य मजकुरावर जा',
    eyebrow: 'स्वतंत्र रिअल इस्टेट ब्रोकर्ससाठी', headline: 'तुमचा रिअल इस्टेट व्यवसाय, आता ऑनलाइन.',
    intro: 'तुमच्या ब्रँडचे प्रॉपर्टी पेज, WhatsApp शेअरिंग आणि सर्व चौकशी एकाच ठिकाणी. घरे, व्यावसायिक जागा आणि जमीन, प्रत्येक लिस्टिंगला व्यावसायिक ओळख द्या.',
    explore: 'नमुना लिस्टिंग पहा', reassurance: '14 दिवसांची मदतीसह ट्रायल · कार्डची गरज नाही', categories: ['निवासी', 'व्यावसायिक', 'प्लॉट व जमीन'],
    trustItems: [
      ['60 सेकंदात सेटअप', 'कोणत्याही कोडिंगशिवाय'],
      ['WhatsApp-फर्स्ट', '1-टॅप शेअरिंग आणि थेट प्रीव्ह्यू'],
      ['100% सुरक्षित डेटा', 'तुमचे ग्राहक आणि लीड्स खाजगी राहतील'],
      ['0% ब्रोकरेज कमिशन', 'तुमची संपूर्ण कमाई तुमच्याकडेच'],
    ],
    walkthroughEyebrow: 'लिस्टिंगपासून संवादापर्यंत',
    walkthroughTitle: 'PropertyOS कसे काम करते.',
    walkthroughSteps: [
      {
        label: 'लिस्टिंग तयारी',
        title: 'प्रॉपर्टीची माहिती जोडा',
        description: 'फोटो अपलोड करा आणि आवश्यक माहिती भरा: किंमत, ठिकाण, क्षेत्रफळ आणि प्रकार. प्लॅटफॉर्म त्यांना शेअर करण्यायोग्य पेजमध्ये रूपांतरित करतो.',
        previewLabel: 'प्रॉपर्टी फॉर्म',
        previewSub: '₹1.65 कोटी · 3 BHK · बाणेर, पुणे',
      },
      {
        label: 'ब्रँडेड पेज प्रीव्ह्यू',
        title: 'तुमचा ब्रँडेड पेज पहा',
        description: 'प्रत्येक लिस्टिंगवर तुमच्या एजन्सीचे नाव आणि संपर्क माहिती दिसते. मांडणी तपासा, वर्णन सुधारा आणि तयार झाल्यावर प्रकाशित करा.',
        previewLabel: 'थेट पेज',
        previewSub: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'WhatsApp शेअर',
        title: 'WhatsApp वर लिंक शेअर करा',
        description: 'प्रॉपर्टी लिंकसह तयार संदेश कॉपी करा आणि खरेदीदारांना पाठवा. ते तुमचा ब्रँडेड पेज पाहतात — कोणताही तृतीय पक्ष पोर्टल नाही.',
        previewLabel: 'संदेश कॉपी करा',
        previewSub: 'propertyos.in/p/prime-baner 🏡',
      },
      {
        label: 'चौकशी कॅप्चर',
        title: 'माहितीसह फॉलो-अप करा',
        description: 'खरेदीदाराने फॉर्म भरल्यावर, तुम्हाला त्यांचे नाव, नोंद आणि कोणत्या प्रॉपर्टीबद्दल विचारले — सर्व एकाच ठिकाणी मिळते.',
        previewLabel: 'नवीन चौकशी',
        previewSub: 'रोहन एम. · बाणेर 3 BHK · प्रत्यक्ष भेटीची विनंती',
      },
    ],
    walkthroughVisuals: [
      { badge: 'पायरी 01 · माहिती', heading: 'प्रॉपर्टी फॉर्म', meta: '6 फोटो · ₹1.65 कोटी · बाणेर, पुणे', tag: 'ऑटो-फॉर्मेट' },
      { badge: 'पायरी 02 · शेअर', heading: 'ब्रँडेड लाइव्ह पेज', meta: 'propertyos.in/p/prime-baner', tag: '1-क्लिक WhatsApp' },
      { badge: 'पायरी 03 · चौकशी', heading: 'थेट ग्राहक चौकशी', meta: 'रोहन एम. • प्रत्यक्ष भेटीची विनंती', tag: 'झटपट अलर्ट' },
    ],
    waDemoEyebrow: 'WHATSAPP शेअरिंग — कसे काम करते',
    waDemoTitle: 'चार पायऱ्यांमध्ये प्रॉपर्टी शेअर करा.',
    waDemoNote: 'हे एक नियंत्रित उदाहरण आहे. कोणताही संदेश आपोआप पाठवला जात नाही.',
    waDemoSteps: [
      {
        label: 'तयारी',
        heading: 'शेअर करण्यासाठी प्रॉपर्टी निवडा',
        body: 'डॅशबोर्डमधून लिस्टिंग निवडा. PropertyOS ब्रँडेड पेज लिंकसह तयार संदेश तयार करतो.',
        visual: 'बाणेरमधील बाग असलेले घर · ₹1.65 कोटी · 3 BHK',
      },
      {
        label: 'संदेश कॉपी करा',
        heading: 'तयार संदेश कॉपी करा',
        body: 'प्रॉपर्टी लिंकसह संदेश आधीच लिहिला आहे. "कॉपी करा" दाबा आणि कोणत्याही WhatsApp संभाषणात पेस्ट करा.',
        visual: 'नमस्कार! बाणेर, पुण्यातील हे 3 BHK पहा:\npropertyos.in/p/prime-baner 🏡\nभेट द्यायची असल्यास कळवा.',
      },
      {
        label: 'खरेदीदार प्रीव्ह्यू',
        heading: 'खरेदीदार तुमचा ब्रँडेड पेज उघडतो',
        body: 'लिंक तुमच्या ब्रँडेड लिस्टिंग पेजवर उघडते — फोटो, किंमत, माहिती आणि चौकशी फॉर्म. तुमचे नाव आणि नंबर सर्वात पुढे.',
        visual: 'propertyos.in/p/prime-baner',
      },
      {
        label: 'चौकशी संदर्भ',
        heading: 'तुम्ही संदर्भासह चौकशी पाहता',
        body: 'खरेदीदाराने फॉर्म भरल्यावर, तुम्हाला त्यांचे नाव, नोंद आणि कोणत्या लिस्टिंगबद्दल विचारले मिळते — वारंवार विचारण्याची गरज नाही.',
        visual: 'रोहन एम. · "या वीकेंडला प्रत्यक्ष पाहायचे आहे." · बाणेर 3 BHK',
      },
    ],
    waDemoCopy: 'संदेश कॉपी करा',
    waDemoCopied: 'कॉपी झाले!',
    waDemoCopyError: 'कॉपी झाले नाही. मजकूर निवडून हाताने कॉपी करा.',
    aiDemoEyebrow: 'AI च्या मदतीने वर्णन',
    aiDemoTitle: 'माहितीवरून मिनिटांत मसुदा.',
    aiDemoNote: 'उदाहरण आउटपुट — प्रकाशित करण्यापूर्वी नेहमी तथ्ये तपासा.',
    aiDemoLabel: 'उदाहरण आउटपुट',
    aiDemoInputs: { type: 'प्रॉपर्टीचा प्रकार', bedrooms: 'बेडरूम', area: 'क्षेत्रफळ', location: 'ठिकाण', price: 'किंमत' },
    aiDemoOptions: { type: ['निवासी', 'व्यावसायिक', 'जमीन'], bedrooms: ['1 BHK', '2 BHK', '3 BHK', '4+ BHK', 'लागू नाही'] },
    aiDemoDefaults: { type: 'निवासी', bedrooms: '3 BHK', area: '1,460 चौ. फूट', location: 'बाणेर, पुणे', price: '₹1.65 कोटी' },
    aiDemoOutput: 'पुण्यातील बाणेर परिसरात उत्तम प्रकारे सांभाळलेल्या 3 BHK अपार्टमेंटमध्ये तीन बेडरूम, एक बैठकीची खोली आणि स्वयंपाकघर आहे. क्षेत्रफळ 1,460 चौ. फूट आहे. किंमत ₹1.65 कोटी. बाणेरमध्ये मुख्य मार्गांशी चांगली जोडणी आहे. कुटुंब आणि नोकरदारांसाठी योग्य. प्रत्यक्ष भेटीसाठी संपर्क करा.',
    aiDemoOutputLabel: 'मसुदा वर्णन',
    aiDemoDisclaimer: 'प्रकाशित करण्यापूर्वी सर्व तथ्ये — किंमत, क्षेत्रफळ, ठिकाण आणि सुविधा — तपासा. मसुदा एक सुरुवात आहे, सत्यापित लिस्टिंग नाही.',
    pricingBadges: { proBadge: 'फाउंडिंग ऑफर — पहिले 100 ब्रोकर्स', zeroCut: 'लीड्स आणि व्यवहारांवर 0% कमिशन' },
    portfolioEyebrow: 'प्रत्येक लिस्टिंगवर तुमचा ब्रँड', portfolioTitle: 'उत्तम पहिली छाप. पुढचे पाऊल स्पष्ट.', portfolioIntro: 'तीन प्रकारच्या प्रॉपर्टी पेजची उदाहरणे पहा.', sample: 'नमुना पोर्टफोलिओ', agency: 'प्राइम रिअल्टी', agencyLocation: 'पुणे, महाराष्ट्र',
    sampleNote: 'लिस्टिंग आणि छायाचित्रे केवळ उदाहरणे आहेत. या प्रॉपर्टी विक्री किंवा भाड्याने उपलब्ध नाहीत.', all: 'सर्व प्रॉपर्टी', filter: 'प्रॉपर्टीचा प्रकार', view: 'प्रॉपर्टी पहा', details: 'प्रॉपर्टीची माहिती',
    titles: ['बाणेरमधील बाग असलेले घर', 'खराडीमधील कार्यालय', 'मुळशीजवळील जमीन'], locations: ['बाणेर, पुणे', 'खराडी, पुणे', 'मुळशी, पुणे'], prices: ['₹1.65 कोटी', '₹85,000 / महिना', '₹72 लाख'], statuses: ['विक्रीसाठी', 'लीजसाठी', 'विक्रीसाठी'],
    specs: [['3 बेडरूम', '1,460 चौ. फूट', 'राहण्यासाठी तयार'], ['1,200 चौ. फूट', 'कार्यालयीन जागा', 'फर्निचरशिवाय'], ['4,000 चौ. फूट', 'जमीन', 'रस्त्याची सोय']],
    descriptions: ['बाग आणि प्रकाशमान खोल्या असलेल्या घराचे उदाहरण.', 'क्षेत्रफळ, फर्निचर आणि लीजच्या किमतीसह कार्यालयाचे उदाहरण.', 'क्षेत्रफळ आणि रस्त्याच्या माहितीसह जमिनीचे उदाहरण.'],
    createLike: 'स्वतःची लिस्टिंग तयार करा', copy: 'नमुना लिंक कॉपी करा', copied: 'लिंक कॉपी झाली', copyError: 'लिंक कॉपी झाली नाही. ब्राउझरमधील पत्ता कॉपी करा.',
    howEyebrow: 'लिस्टिंगपासून संवादापर्यंत', howTitle: 'एक सोपी प्रक्रिया.', steps: [['प्रॉपर्टी जोडा', 'फोटो, किंमत, ठिकाण, क्षेत्रफळ आणि प्रॉपर्टीचा प्रकार भरा.'], ['तपासा आणि शेअर करा', 'वर्णन सुधारा, ब्रँडेड पेज प्रकाशित करा आणि WhatsApp वर लिंक पाठवा.'], ['माहितीसह फॉलो-अप करा', 'आलेल्या चौकशा आणि खरेदीदारांची कृती पहा, मग पुढील संवादाची तयारी करा.']],
    featuresEyebrow: 'तुमच्या रोजच्या कामासाठी', featuresTitle: 'शेअर केल्यानंतरही उपयोगी.', features: [['तुमची ओळख सर्वात पुढे', 'प्रत्येक पेजवर एजन्सीचे नाव, लोगो आणि संपर्क माहिती दाखवा.'], ['माहितीसह WhatsApp', 'एका लिंकवरून खरेदीदाराला फोटो, माहिती आणि चौकशीचा पर्याय द्या.'], ['AI च्या मदतीने वर्णन', 'तुम्ही दिलेल्या माहितीवरून मसुदा तयार करा. प्रकाशित करण्यापूर्वी तथ्ये तपासा.'], ['चौकशीनंतर पुढचे पाऊल', 'लीड, नोंदी आणि टप्पे एकत्र ठेवा. पेज व्ह्यू हा रुचीचा संकेत आहे, निश्चित खरेदीदार नाही.']],
    priceEyebrow: 'फाउंडिंग ब्रोकर प्रोग्राम', priceTitle: 'एका खऱ्या प्रॉपर्टीपासून सुरुवात करा.', priceIntro: 'स्वतःच्या ब्रँडसह काम करून पहा. पहिल्या तीन लिस्टिंगसाठी मदत मिळवा.',
    trialTitle: 'मदतीसह ट्रायल', trialPrice: 'मोफत', trialPeriod: '14 दिवसांसाठी', trialFeatures: ['10 लिस्टिंगपर्यंत', '2 वापरकर्त्यांपर्यंत', '50 लीडपर्यंत', 'ब्रँडेड पेज आणि शेअरिंग'],
    paidTitle: 'फाउंडिंग प्रो', paidPrice: '₹499', paidPeriod: 'दरमहा · मदतीसह सक्रियकरण', paidFeatures: ['100 लिस्टिंगपर्यंत', '5 वापरकर्त्यांपर्यंत', '500 लीडपर्यंत', 'लिस्टिंग आणि चौकशीचे विश्लेषण'], priceNote: 'प्रो सक्रिय करण्यासाठी सपोर्टशी बोला. अपग्रेड करण्यापूर्वी लागू कर आणि अतिरिक्त सेवा शुल्क निश्चित करा.', talk: 'प्रोबद्दल चर्चा करा',
    faqTitle: 'सुरुवात करण्यापूर्वी.', faqs: [
      ['हे फक्त निवासी ब्रोकर्ससाठी आहे का?', 'नाही. निवासी, व्यावसायिक आणि जमिनीच्या लिस्टिंग करता येतात.'],
      ['14 दिवसांनंतर काय होते?', 'मदतीसह ट्रायल 14 दिवसांची आहे. सशुल्क प्रवेशासाठी सपोर्टशी बोला.'],
      ['WhatsApp ऑटोमेशन आणि AI अमर्यादित आहे का?', 'अमर्यादित वापराचे आश्वासन नाही. ऑटोमेशनसाठी प्रदात्याचे सेटअप आवश्यक आहे.'],
      ['माझा स्वतःचा डोमेन मिळेल का?', 'ब्रँडेड प्रॉपर्टी पेज उपलब्ध आहेत. कस्टम डोमेन पुढील योजना आहे.'],
      ['पेज पाहणाऱ्याची ओळख समजते का?', 'नाही. फॉलो-अपसाठी आलेल्या चौकशा वापरा.'],
      ['3D भेटी आणि कायदेशीर सेवा कधी?', 'या भविष्यातील दिशा आहेत, सध्या समाविष्ट नाहीत.'],
    ], finalTitle: 'पुढच्या लिस्टिंगपासून सुरुवात करा.', finalText: 'तुमचे फोटो आणि प्रॉपर्टीची माहिती आणा. सुरुवात करण्यासाठी आम्ही मदत करू.', footer: 'रिअल इस्टेट व्यावसायिकांसाठी बनवलेले.', footerLinks: ['सपोर्ट', 'गोपनीयता', 'अटी', 'परतावा'],
  },
};

export const SAMPLE_IMAGES = [
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85',
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=85',
];

export function signupHref(language: Language, source: string) {
  return `/auth/signup?${new URLSearchParams({ lang: language, source })}`;
}
