export const SIGNUP_COPY = {
  en: {
    program: 'Founding Broker Program', title: 'Publish your first professional property page.', intro: 'Start with your brokerage identity. We will help with branding, your first listing and your first WhatsApp share.', benefits: ['14-day assisted trial with no card', 'Your branding on every property page', 'Buyer actions visible in your workspace'],
    eyebrow: 'Create broker workspace', heading: 'Start your assisted trial', registered: 'Already registered?', login: 'Sign in', company: 'Brokerage or agency name', name: 'Your full name', phone: 'Phone and WhatsApp', email: 'Email address', password: 'Password', passwordHint: 'At least 8 characters', language: 'Language', referral: 'Referral code', optional: 'Optional', agree: 'I agree to the', terms: 'Terms', and: 'and', privacy: 'Privacy Notice', consentEnd: 'required to operate my workspace.', marketing: 'Send trial guidance and demo reminders on WhatsApp. I can opt out anytime.', creating: 'Creating workspace…', create: 'Create workspace', private: 'Account data stays private', support: 'WhatsApp setup support', required: 'Complete all required fields to create your workspace.', consentError: 'Accept the Terms and Privacy Notice to continue.', passwordError: 'Use a password with at least 8 characters.',
  },
  hi: {
    program: 'फाउंडिंग ब्रोकर प्रोग्राम', title: 'अपना पहला पेशेवर प्रॉपर्टी पेज पब्लिश करें।', intro: 'अपनी एजेंसी की पहचान से शुरू करें। ब्रांडिंग, पहली लिस्टिंग और WhatsApp शेयर में हम मदद करेंगे।', benefits: ['14 दिन का सहायता सहित ट्रायल, बिना कार्ड', 'हर प्रॉपर्टी पेज पर आपका ब्रांड', 'वर्कस्पेस में खरीदारों की गतिविधि'],
    eyebrow: 'ब्रोकर वर्कस्पेस बनाएं', heading: 'सहायता सहित ट्रायल शुरू करें', registered: 'पहले से अकाउंट है?', login: 'लॉग इन', company: 'ब्रोकरेज या एजेंसी का नाम', name: 'आपका पूरा नाम', phone: 'फ़ोन और WhatsApp', email: 'ईमेल पता', password: 'पासवर्ड', passwordHint: 'कम से कम 8 अक्षर', language: 'भाषा', referral: 'रेफ़रल कोड', optional: 'वैकल्पिक', agree: 'मैं वर्कस्पेस चलाने के लिए आवश्यक', terms: 'शर्तों', and: 'और', privacy: 'गोपनीयता सूचना', consentEnd: 'से सहमत हूं।', marketing: 'WhatsApp पर ट्रायल सहायता और डेमो रिमाइंडर भेजें। मैं कभी भी बंद कर सकता हूं।', creating: 'वर्कस्पेस बन रहा है…', create: 'वर्कस्पेस बनाएं', private: 'अकाउंट की जानकारी निजी रहती है', support: 'WhatsApp सेटअप में सहायता', required: 'वर्कस्पेस बनाने के लिए सभी आवश्यक जानकारी भरें।', consentError: 'जारी रखने के लिए शर्तें और गोपनीयता सूचना स्वीकार करें।', passwordError: 'पासवर्ड में कम से कम 8 अक्षर रखें।',
  },
  mr: {
    program: 'फाउंडिंग ब्रोकर प्रोग्राम', title: 'तुमचे पहिले व्यावसायिक प्रॉपर्टी पेज प्रकाशित करा.', intro: 'तुमच्या एजन्सीच्या ओळखीपासून सुरुवात करा. ब्रँडिंग, पहिली लिस्टिंग आणि WhatsApp शेअरमध्ये आम्ही मदत करू.', benefits: ['14 दिवसांची मदतीसह ट्रायल, कार्डशिवाय', 'प्रत्येक प्रॉपर्टी पेजवर तुमचा ब्रँड', 'वर्कस्पेसमध्ये खरेदीदारांच्या कृती'],
    eyebrow: 'ब्रोकर वर्कस्पेस तयार करा', heading: 'मदतीसह ट्रायल सुरू करा', registered: 'आधीच खाते आहे?', login: 'लॉग इन', company: 'ब्रोकरेज किंवा एजन्सीचे नाव', name: 'तुमचे पूर्ण नाव', phone: 'फोन आणि WhatsApp', email: 'ईमेल पत्ता', password: 'पासवर्ड', passwordHint: 'किमान 8 अक्षरे', language: 'भाषा', referral: 'रेफरल कोड', optional: 'ऐच्छिक', agree: 'वर्कस्पेस चालवण्यासाठी आवश्यक', terms: 'अटी', and: 'आणि', privacy: 'गोपनीयता सूचना', consentEnd: 'मला मान्य आहेत.', marketing: 'WhatsApp वर ट्रायल मार्गदर्शन आणि डेमो स्मरणपत्रे पाठवा. मी कधीही बंद करू शकतो.', creating: 'वर्कस्पेस तयार होत आहे…', create: 'वर्कस्पेस तयार करा', private: 'खात्याची माहिती खाजगी राहते', support: 'WhatsApp सेटअपसाठी मदत', required: 'वर्कस्पेस तयार करण्यासाठी सर्व आवश्यक माहिती भरा.', consentError: 'पुढे जाण्यासाठी अटी आणि गोपनीयता सूचना स्वीकारा.', passwordError: 'पासवर्डमध्ये किमान 8 अक्षरे वापरा.',
  },
};
